LABEL_MAP = {
    "road": 0,
    "sidewalk": 1,
    "building": 2,
    "wall": 3,
    "fence": 4,
    "pole": 5,
    "traffic light": 6,
    "traffic sign": 7,
    "vegetation": 8,
    "terrain": 9,
    "sky": 10,
    "person": 11,
    "rider": 12,
    "car": 13,
    "truck": 14,
    "bus": 15,
    "motorcycle": 16,
    "bicycle": 17,
    "autorickshaw": 18,
    "animal": 19,
    "caravan": 20,
    "trailer": 21,
    "train": 22,
    "parking": 23,
    "rail track": 24,
    "curb": 25,
    "bridge": 26,
    "tunnel": 27,
    "billboard": 28,
    "guard rail": 29,
    "polegroup": 30,
    "drivable fallback": 31,
    "non-drivable fallback": 32,
    "vehicle fallback": 33,
    "obs-str-bar-fallback": 34,
    "fallback background": 35,
    "out of roi": 36,
    "rectification border": 37,
    "license plate": 38,
    "ego vehicle": 39,
    "ground": 40,
    "unlabeled": 41,
}

# aliases appearing in IDD-AW
LABEL_MAP.update({
    "autorickshaw_new": LABEL_MAP["autorickshaw"],
    "billboard_new": LABEL_MAP["billboard"],
    "curb_new": LABEL_MAP["curb"],
    "drivable fallback_new": LABEL_MAP["drivable fallback"],
    "obs-str-bar-fallback_new": LABEL_MAP["obs-str-bar-fallback"],
    "vehicle fallback_new": LABEL_MAP["vehicle fallback"],
})

NUM_CLASSES = 42
IGNORE_INDEX = 255